// A curated list of major Indonesian cities and regencies (kota/kabupaten),
// grouped roughly by province, for use in the candidate application form's
// City dropdown. Not exhaustive — covers the cities candidates are
// overwhelmingly likely to select — but easy to extend.
export const INDONESIAN_CITIES: string[] = [
  // DKI Jakarta
  "Jakarta Pusat",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Kepulauan Seribu",

  // Banten
  "Tangerang",
  "Tangerang Selatan",
  "Kabupaten Tangerang",
  "Serang",
  "Kabupaten Serang",
  "Cilegon",
  "Pandeglang",
  "Lebak",

  // Jawa Barat
  "Bandung",
  "Kabupaten Bandung",
  "Kabupaten Bandung Barat",
  "Cimahi",
  "Bekasi",
  "Kabupaten Bekasi",
  "Bogor",
  "Kabupaten Bogor",
  "Depok",
  "Sukabumi",
  "Kabupaten Sukabumi",
  "Cianjur",
  "Garut",
  "Tasikmalaya",
  "Kabupaten Tasikmalaya",
  "Ciamis",
  "Banjar",
  "Cirebon",
  "Kabupaten Cirebon",
  "Kuningan",
  "Majalengka",
  "Sumedang",
  "Indramayu",
  "Subang",
  "Purwakarta",
  "Karawang",

  // Jawa Tengah
  "Semarang",
  "Kabupaten Semarang",
  "Surakarta (Solo)",
  "Salatiga",
  "Magelang",
  "Kabupaten Magelang",
  "Pekalongan",
  "Kabupaten Pekalongan",
  "Tegal",
  "Kabupaten Tegal",
  "Kudus",
  "Pati",
  "Jepara",
  "Rembang",
  "Blora",
  "Grobogan",
  "Demak",
  "Kendal",
  "Batang",
  "Pemalang",
  "Brebes",
  "Banyumas (Purwokerto)",
  "Cilacap",
  "Kebumen",
  "Purworejo",
  "Wonosobo",
  "Temanggung",
  "Boyolali",
  "Klaten",
  "Sukoharjo",
  "Wonogiri",
  "Karanganyar",
  "Sragen",

  // DI Yogyakarta
  "Yogyakarta",
  "Bantul",
  "Sleman",
  "Kulon Progo",
  "Gunungkidul",

  // Jawa Timur
  "Surabaya",
  "Malang",
  "Kabupaten Malang",
  "Batu",
  "Kediri",
  "Kabupaten Kediri",
  "Blitar",
  "Kabupaten Blitar",
  "Mojokerto",
  "Kabupaten Mojokerto",
  "Madiun",
  "Kabupaten Madiun",
  "Pasuruan",
  "Kabupaten Pasuruan",
  "Probolinggo",
  "Kabupaten Probolinggo",
  "Jember",
  "Banyuwangi",
  "Bojonegoro",
  "Tuban",
  "Lamongan",
  "Gresik",
  "Sidoarjo",
  "Mojokerto",
  "Ngawi",
  "Magetan",
  "Ponorogo",
  "Pacitan",
  "Trenggalek",
  "Tulungagung",
  "Nganjuk",
  "Jombang",
  "Bangkalan",
  "Sampang",
  "Pamekasan",
  "Sumenep",
  "Situbondo",
  "Bondowoso",
  "Lumajang",

  // Bali & Nusa Tenggara
  "Denpasar",
  "Badung",
  "Gianyar",
  "Tabanan",
  "Klungkung",
  "Bangli",
  "Karangasem",
  "Buleleng",
  "Jembrana",
  "Mataram",
  "Kupang",

  // Sumatera
  "Medan",
  "Binjai",
  "Pematangsiantar",
  "Tebing Tinggi",
  "Deli Serdang",
  "Padang",
  "Bukittinggi",
  "Padang Panjang",
  "Payakumbuh",
  "Pekanbaru",
  "Dumai",
  "Batam",
  "Tanjungpinang",
  "Jambi",
  "Palembang",
  "Lubuklinggau",
  "Prabumulih",
  "Bengkulu",
  "Bandar Lampung",
  "Metro",
  "Banda Aceh",
  "Langsa",
  "Lhokseumawe",
  "Sabang",

  // Kalimantan
  "Pontianak",
  "Singkawang",
  "Palangkaraya",
  "Banjarmasin",
  "Banjarbaru",
  "Samarinda",
  "Balikpapan",
  "Bontang",
  "Tarakan",

  // Sulawesi
  "Makassar",
  "Parepare",
  "Palopo",
  "Manado",
  "Bitung",
  "Tomohon",
  "Kotamobagu",
  "Palu",
  "Kendari",
  "Bau-Bau",
  "Gorontalo",
  "Mamuju",

  // Maluku & Papua
  "Ambon",
  "Tual",
  "Ternate",
  "Tidore Kepulauan",
  "Jayapura",
  "Sorong",
  "Manokwari",

  "Other / Lainnya",
];